version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies for frontend..."
      - cd frontend
      - npm install
  build:
    commands:
      - echo "Building the React production bundle..."
      - npm run build
artifacts:
  base-directory: frontend/build
  files:
    - '**/*'
